[custom]
;不要随意改变关键字，否则会导致出错
;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/BanProgramAD.list
ruleset=🇺🇲 美区AI,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/AiDomain.list
ruleset=👨‍💻 Developer,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Developer.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Telegram.list
ruleset=🔒 Web3,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Web3.list
ruleset=🎬 Media,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Spotify.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Steam.list
ruleset=🎬 Media,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/YouTube.list
ruleset=📚 Edu,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Khan.list
ruleset=📚 Edu,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Edutools.list
ruleset=🎬 Media,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Netflix.list
ruleset=🎬 Media,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/NetflixIP.list
ruleset=🎬 Media,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/DisneyPlus.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/Bilibili.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Ruleset/BilibiliHMT.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaMedia.list
ruleset=🎬 Media,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/szkane/ClashRuleSet/main/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=🇺🇲 美区AI`select`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🚀 节点选择`[]🫙 自定义`.*
custom_proxy_group=👨‍💻 Developer`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=🔒 Web3`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=🎬 Media`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=📚 Edu`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🫙 自定义`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🇺🇲 美国节点`[]🇺🇲 美国手动`[]🚀 节点选择`[]DIRECT`[]🫙 自定义`.*
custom_proxy_group=🇺🇲 美国节点`url-test`.*`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇺🇲 美国手动`select`[]DIRECT`.*
custom_proxy_group=🫙 自定义`select`.*
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
